### ISSUE TITLE
FR: Smooth only selected tracks

### ISSUE THREAD

**Issue by daxliniere** [mattshepcar/easyeda-round-tracks#11]
Thanks for this great extension. I really love the old-school look of curved tracks (guess which era of circuit boards I grew up in ;) )
I like the way it creates a copy of the PCB so you can re-edit the original straight-line version, but would it be possible to modify the script so that we have an option to smooth just selected tracks?

**Comment by mattshepcar** [comment]
Thanks. I'm probably not going to add any new features to this now as I've mostly moved onto using EasyEDA Pro which currently doesn't support extensions.

**Comment by daxliniere** [comment]
Hey Matt,
Okay, sure, I can understand that.
Perhaps we can pin this for the day the "pro" version support extensions?

Also, what is it about the Pro version that made you switch?

Take care,
Dax.

**Comment by daxliniere** [comment]
Hey again, Matt. Quick question: Do you know of any ill side-effects of running Smooth Tracks on a PCB that has already had Smooth Tracks applied?
I assumed it would either confuse or mess up the layout, but I just tried it and it seems fine. (Though I've not yet tried to edit anything so not sure if, for example, a million superfluous points might have been created.)

Thanks again,
Dax.

**Comment by mattshepcar** [comment]
I'm not really sure tbh. The intended workflow was that you always edit the original PCB and just run 'smooth tracks' as a final step before generating your production gerber files.

**Comment by daxliniere** [comment]
Yeah, unfortunately due to the way that tracks are modified when smoothing is applied, it meant I needed to rework the smoothed PCB and at some point, I got sick of updating the original PCB layout and just updated the smoothed one.
IIRC, this was caused by issue #12 which you solved, so hopefully not a problem going forward.

Is there any way you can attach some unique property to the tracks your extension creates? Does EasyEDA have scope for that?

**Comment by mattshepcar** [comment]
The teardrops and fillets (the curves between three-way intersections or places where tracks of differing widths meet) are flagged as 'teardrops' so you can use the standard teardrop tool to remove all of those.  I'm not sure if EasyEDA would throw away any additional properties on tracks that it didn't understand but maybe it would be possible to store information somewhere to be able to "unsmooth" tracks.

**Comment by daxliniere** [comment]
Well, let me know if you get around to trying something and if you need a hand testing.
Cheers for the reply, Matt! :)
