### ISSUE TITLE
Transitions between tracks of different widths

### ISSUE THREAD

**Issue by daxliniere** [mattshepcar/easyeda-round-tracks#12]
I've noticed that there can be 'overshoot' when smoothing 2 tracks of different widths. For example make a vertical track that is 3mm wide, then add a horizontal track of 1.5mm that is connected to the first. (right-angle)

You'll see that there will be 3mm thick curves which overshoot the expected boundaries.

Happy to provide more information/help with beta testing if you would like.

All the best,
Dax.

**Comment by mattshepcar** [comment]
I think I've fixed it. Attach some screenshots if it's still going wrong.

**Comment by daxliniere** [comment]
Hey Matt!
Yes, can confirm that your fix has solved the issue. Lines are now looking great!

Thanks again,
Dax.
